import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import StyledComponents setting
import StyledComponentsRegistry from "../lib/registry";
import GlobalThemeWrapper from "../lib/GlobalThemeWrapper";
// import components
import BodyWrapper from "../components/BodyWrapper";
import Navbar from "./components/Navbar/Navbar";

const inter = Inter({ subsets: ["greek"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <StyledComponentsRegistry>
        <GlobalThemeWrapper>
          <BodyWrapper>
            <Navbar />
            {children}
          </BodyWrapper>
        </GlobalThemeWrapper>
      </StyledComponentsRegistry>
    </html>
  );
}
